config/routes.rb
Rails.application.routes.draw do


  resources :articles do
    resources :comments
  end
  resources :authors,       except: [ :destroy ]
  resources :tags
  root 'articles#show'

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  has_many :taggings
  has_many :tags, :through => :taggings
  belongs_to :author

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  validates :title, presence: true,
            length: { minimum: 5 }


  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def record_article_view
    self.view_count = self.view_count + 1
  end

end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, :through => :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: [:show]
  
  
  def index
    @articles = Article.all
    @authors = Author.all
    if current_user.id == 1
      @is_admin = true
    end
  end

  def new
    @article = Article.new
  end

 def edit
   @article = Article.find(params[:id])
   if @article.author_id != current_user.id and current_user.id != 1
     redirect_to articles_path
   end
 
 end

 def create
   @author = Author.find(current_user.id)
   @article = @author.articles.new(article_params)
   @article.date = Time.now.year.to_s + "-" + Time.now.month.to_s + "-" + Time.now.day.to_s
   if @article.save
     redirect_to @article
   else
     render 'new'
   end
 end

 def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    flash.notice = "Article '#{@article.title}' updated!"
    redirect_to @article
  else
    render 'edit'
  end
 end

 def show
   @articles = Article.all
   @tags = Tag.all
   if params[:id]
     @article = Article.find(params[:id])
     @author = @article.author
     @article.record_article_view
     @article.save
   else
     if @articles.last
       @article = @articles.last
       @author = @article.author
       @article.record_article_view
       @article.save
     end
   end
   if @articles.size > 2
     @top_three = get_most_viewed_articles
   end
 end

 def destroy
   @article = Article.find(params[:id])
   if @article.author_id != current_user.id and current_user.id != 1
     redirect_to articles_path
   else
     @article.destroy
     redirect_to articles_path
   end
 end

 private
 def article_params
   params.require(:article).permit(:title, :text, :tag_list, :image)
 end

 def get_most_viewed_articles
   @top_three = @articles.sort_by &:view_count
   @top_three = @top_three.reverse[0..2]
 end
end
                                                                   

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :zero_authors_or_authenticated, only: [:new, :create]
  before_action :require_login, except: [:new, :create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
    if @author.id != current_user.id and current_user.id != 1
      redirect_to authors_path
    end
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end

    def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, except: [:create]
                                 
  def create
    date = Time.now.year.to_s + "-" + Time.now.month.to_s + "-" + Time.now.day.to_s
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.date = date
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all
    if @articles.last
      @article = @articles.last
    else
      redirect_to "/home/empty.html"
    end
  end

  def empty
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_login, only: [:index, :destroy]
  
  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
    if @tags.last
      @tags
    else
      render template: "tags/none"
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path

  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/empty.html.erb
<p>There are no posts to display, please try again soon.
  </p>

app/views/articles/index.html.erb
<h2>Admin Panel</h2>

<%= link_to 'New article', new_article_path %>

<br />
<br />
<table>
  <tr>
    <th>Date</th>
    <th>Author</th>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.reverse.each do |article| %>
  <tr>
      <td><%= article.date %></td>
      <% @authors.each do |author| %>
        <% if article.author_id == author.id %>
          <td><%= author.username %></td>
	  <% end %>
	<% end %>
     
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>

      <% if article.author_id == current_user.id or @is_admin %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article),
		method: :delete,
		data: { confirm: 'Are you sure?' } %></td>

      <% else %>
      <td>Edit</td>
      <td>Destroy</td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>


<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% if @article %>
  

<p>
  <%= @article.date %> <strong><%= @article.title %></strong>
</p>
<p>
  By: <%= @author.username %>
</p>
 
<p>
  <%= @article.text %>
</p>

<p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
  <% end %>

</p>

<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

    <% if logged_in? %>
      <%= link_to 'Edit', edit_article_path(@article) %> |
      <%= link_to 'Article List', articles_path %>
    <% end %>

<h2>Add a comment:</h2>

  <%= render 'comments/form' %>


<h2>Comments: (<%= @article.comments.size - 1 %>) </h2>

<%= render @article.comments %>

<%= @article.inspect %>

<% else %>
  <p>
    There are no posts to display, please try again soon.
  </p>
  <% end %>

  <br />
  <br />


<%= render 'layouts/categories' %>
<% if @articles.size > 2 %>
  <%= render 'layouts/popular' %>
<% end %>

app/views/author_sessions/new.html.erb
<h2>Login</h2>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :author_username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :author_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :author_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_comment.html.erb
<% if comment.id %>

  <p>
    <%= comment.date %> <strong><%= comment.commenter %></strong>
  </p>
 
  <p>
    <%= comment.body %>
  </p>

  <p>
    <% if logged_in? %>
      <%= link_to 'Destroy Comment', [comment.article, comment],
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
    <% end %>

  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>My Blog</h1>

<br />

<p>
<%= @article.date %> <strong><%= @article.title %></strong>
</p>

<p>
<%= @article.text %>
</p>
<br />

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <%= comment.body %>
  </p>
  <% end %>

<% if @article %>

  <h2>Add a comment:</h2>
  
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>
  <% end %>

 

app/views/tags/index.html.erb
<h2>Tags</h2>

<% @tags.each do |tag| %>
  <p>
    <%= link_to tag.name, tag_path(tag.id) %>
    <% if logged_in? %>
      <%= link_to 'Delete', tag_path(tag.id),
	  method: :delete,
	  data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <% end %>

app/views/tags/none.html.erb
<h2>Tags</h2>

<p>There are currently no tags to display</p>

app/views/tags/show.html.erb
<h2>Articles Tagged with <%= @tag.name %></h2>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>